### PR TITLE
Initial international phone input implementation

### LINKED ISSUE #129: App - Country Code Phone Number stuff
https://www.npmjs.com/package/react-phone-number-input

### PR DESCRIPTION
**Pull request by portoaj**
### Adminstrative Info

Closes #129 

### Changes

What changes did you make?

- Added an international phone number package: https://www.npmjs.com/package/react-native-phone-number-input
- Replaced phone inputs on addJob page

### Replacing phone inputs in the rest of the app (such as driver registration)

How did you confirm your changes worked?

- Printed to console to make sure input was properly outputted

### Confirmation of Change

Screenshot 2023-05-05 at 4 22 44 PM

Screenshot 2023-05-05 at 4 23 02 PM

### CODE REVIEW

**Comment by portoaj** [comment]
Screenshot 2023-05-12 at 4 28 38 PM
Updated the styling to better match the rest of the frontend, extracted a component to hold the phone number input, and added it to the rest of the pages that needed a phone number input.

**Review by alexzhang1618 — COMMENTED** [review]
Changes LGTM! I just want to hold off on this before we merge in SMS verification since there are additional phone input fields we probably want to update there as well

**Comment by alexzhang1618** [comment]
Let's make this compatible with #138 then good to merge!

**Review by alexzhang1618 — APPROVED** [review]
LGTM 🤩

**Pull request merged**
